### ISSUE TITLE
userspace: detect weak externalization for non static functions

### ISSUE THREAD

**Issue by marcosps** [SUSE/clang-extract#110]
Currently clang-extract only detects a weak symbol on kernel if the symbol comes from ``vmlinux`` itself and a prototype is defined for the symbol.

For userspace code we would need to recognize a function that is local to a file, not static and without a prototype to be also weak externalized.

**Comment by giulianobelinassi** [comment]
What was the rational of this? The description doesn't describe much. I remember this was some problem that could only happen on ULP.

**Comment by marcosps** [comment]
I remember that I opened the bug while we were discussing about userspace livepatching, but I don't remember specifically what it was about... :P
