### ISSUE TITLE
Support IBT usecase on kernel

### ISSUE THREAD

**Issue by marcosps** [SUSE/clang-extract#33]
When IBT is enabled on linux kernel, we can't use externalized variables + kallsyms anymore. Support the klp-convert way of declaring private symbols. I'll work on it soon.

**Comment by marcosps** [comment]
Patches sent for review. Hopefully we can have it merged soon and so start supporting livepatches for upstream kernels

**Comment by giulianobelinassi** [comment]
There are two testcases failing.
testsuite/linux/ibt-2.c and testsuite/linux/ibt-3.c

**Comment by marcosps** [comment]
Faster than light!

**Comment by marcosps** [comment]
We still have some problems when generating the sample livepatch using the "IBT" method. Checking what's wrong...

**Comment by marcosps** [comment]
Some things that we should still work out:

- [ ] remove parentheses from the exported symbol name

**Comment by marcosps** [comment]
ibt-2 is now passing, and the "issue" reported on ibt-3.c is not really an issue right now, so we can work on it in the future.
