### ISSUE TITLE
clang-create creates file with bogus name

### ISSUE THREAD

**Issue by andreas-schwab** [SUSE/clang-extract#60]
$ cat hello.c 
#include <stdio.h>
#include <locale.h>

void
hello (void)
{
  if (fprintf (stderr, "Hello World!\n") == EOF)
    perror ("fprintf");
}

int
main (void)
{
  setlocale (LC_ALL, "");
  hello ();
}
$ clang-extract -DCE_EXTRACT_FUNCTIONS=hello hello.c 
In file included from hello.c:1:
In file included from hello.c:1:
In file included from /usr/include/stdio.h:28:
In file included from /usr/include/bits/libc-header-start.h:33:
In file included from /usr/include/features.h:394:
In file included from /usr/include/features-time64.h:21:
/usr/include/bits/timesize.h:19:1: warning: clang-extract: project #include's the same file multiple times. Only the first is registered.
   19 | #include <bits/wordsize.h>
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
$ ls -Q
"hello.CE.c"  "hello.c"  "\377\177"

**Comment by giulianobelinassi** [comment]
I am sorry, but what is the issue here?

**Comment by giulianobelinassi** [comment]
which file?

**Comment by andreas-schwab** [comment]
The one with the bogus name.

**Comment by giulianobelinassi** [comment]
> The one with the bogus name.

which is? can you point it?

**Comment by andreas-schwab** [comment]
^^^^^^^^^^

**Comment by andreas-schwab** [comment]
The one with the bogus name.

**Comment by giulianobelinassi** [comment]
Closing this to the reason of trolling.

This will be reported.
