### ISSUE TITLE
Decompress ELF objects e.g. kernel modules

### ISSUE THREAD

**Issue by marcosps** [SUSE/clang-extract#63]
Curerntly clang-extract doesn't deal with ELF objects that are compressed, like kernel modules. Having this implemented on clang-extract would make it easier to integrate it with different distributions, without having to reset to zstd extraction on /lib/modules for example.

**Comment by giulianobelinassi** [comment]
We have two options here:
- Import and link with `libzstd`, then extract the ELF content into a buffer and expand ElfCXX to load it from memory by calling `elf_memory`.
- `vfork` --> `exec` to the `zstd` tool into a temporary file, and use it.

The first option has the disadvantage that libzstd will be placed as a dependency of clang-extract, but we can workaround that by using `dlopen` and `dlsym`. The second option have an disadvantage that it will be clunky and potentially slow.

**Comment by marcosps** [comment]
I was checking libkmod, which can help to extract all current formats that kernel supports. All distros should package libkmod, since it's part of the kmod project (modprobe, modinfo, etc...). I may need more time to think more about it, but if this trully happens, we may be able to create livepatches from people's own /usr/src/linux and /lib/modules, instead of having to complie their own kernels.

(The only missing piece would be compile_commands.json, but that is being worked ATM)

**Comment by marcosps** [comment]
Support for gz and zstd was merged, meaning that we can now handle vmlinux.gz and kernel modules (on some distros) with zstd compressions. We are one step closer to creating livepatches on openSUSE/SLE distros very soon!

I believe that we still need to support lzma (xz), and then we can close this issue.

**Comment by marcosps** [comment]
I believe that we can close this bug, since openSUSE tumbleweed is already covered by gzip and zstd decompression. When adding support to other distros/versions we may need to add support for other compression formats.
