### ISSUE TITLE
Replace all `dynamic_cast<>` for `dyn_cast<>`

### ISSUE THREAD

**Issue by giulianobelinassi** [SUSE/clang-extract#87]
If clang is compiled without RTTY information then dynamic_cast will always fail. Change it to clang's own `dyn_cast<>` which should behave the same

**Comment by Bicheka** [comment]
got it

**Comment by jh991205** [comment]
I have made the changes in pull request #90. Please review the changes at your convenience, and let me know if there are any further adjustments or improvements needed.
